In [48]:
import  xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime,timedelta
import warnings

In [49]:
df=pd.read_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/merged_df_v1.csv')


In [50]:
df

time  latitude  longitude        t2m       mx2t       mn2t  \
0       1981-01-01      27.5       87.5  272.44590  280.96375  264.93085   
1       1981-01-01      27.5       90.0  277.43057  280.59924  275.02722   
2       1981-01-01      27.5       92.5  273.97640  278.73110  269.32446   
3       1981-01-01      25.0       87.5  288.51346  294.98935  283.45917   
4       1981-01-01      25.0       90.0  289.99857  296.68546  285.48462   
...            ...       ...        ...        ...        ...        ...   
184075  2022-12-31      22.5       90.0  291.44186  296.95560  287.66700   
184076  2022-12-31      22.5       92.5  290.00693  296.92117  283.32626   
184077  2022-12-31      20.0       87.5  297.13577  297.48105  296.48117   
184078  2022-12-31      20.0       90.0  296.44460  296.68140  296.25607   
184079  2022-12-31      20.0       92.5  296.53552  296.92690  295.80237   

        rhum_1000hpa  rhum_850hpa  rhum_500hpa       u10  ...  geo_hgt_500hpa  \
0          71.980545    71.431860    58.090637 -0.194943  ...       56112.380   
1          91.592870    91.917410    43.649540 -0.027385  ...       56052.580   
2          78.709800    79.580480    61.536285  0.222168  ...       55991.418   
3          68.094640    34.034214     3.025867  2.514468  ...       56431.170   
4          62.741270    45.546825     3.685225  1.763424  ...       56328.844   
...              ...          ...          ...       ...  ...             ...   
184075     62.377167    35.078110     6.154188 -1.206016  ...       56989.902   
184076     68.681430    40.845684     4.719855 -0.077168  ...       56942.450   
184077     68.472150    39.682310     8.652951 -0.672088  ...       57410.918   
184078     61.102383    30.916985     6.653173 -1.102595  ...       57367.895   
184079     61.845367    32.810894     5.758938  1.753668  ...       57357.047   

        shum_1000hpa  shum_850hpa  shum_500hpa         msl         swvl1  \
0           0.004203     0.004203     0.001123  101491.630  3.795592e-01   
1           0.006046     0.006046     0.000922  101524.625  3.995494e-01   
2           0.004736     0.004673     0.001244  101638.680  3.902917e-01   
3           0.007803     0.003205     0.000099  101454.000  1.768660e-01   
4           0.008299     0.004048     0.000113  101371.190  1.641411e-01   
...              ...          ...          ...         ...           ...   
184075      0.008880     0.003838     0.000277  101785.970  2.226953e-01   
184076      0.008382     0.004143     0.000212  101778.900  2.116297e-01   
184077      0.011673     0.004990     0.000401  101705.970  5.948047e-07   
184078      0.009906     0.003796     0.000316  101741.695  5.948047e-07   
184079      0.009752     0.003920     0.000280  101702.305  5.948047e-07   

           swvl2  temp_1000hpa  temp_850hpa  temp_500hpa  
0       0.365721     293.15018    284.24010    260.50095  
1       0.393815     293.72390    284.79892    259.19534  
2       0.390833     292.92487    284.00497    258.53750  
3       0.199197     290.74564    283.99454    263.61220  
4       0.202003     291.92108    283.47208    262.94626  
...          ...           ...          ...          ...  
184075  0.257471     292.99512    286.31732    266.32822  
184076  0.239111     292.45758    285.81064    266.17575  
184077 -0.000004     295.60860    288.53555    266.92087  
184078 -0.000004     294.90536    288.11154    267.25967  
184079 -0.000004     294.53760    287.52988    267.34183  

[184080 rows x 25 columns]

In [51]:
import pandas as pd

# Assuming df is your DataFrame and 'date_column' is the column you want to convert
df['time'] = pd.to_datetime(df['time'])
# df['time'] = pd.to_datetime(df['time']).dt.date



In [52]:
# def remove_column(df, column_to_remove):
#     # Remove the specified column from the DataFrame
#     df = df.drop(column_to_remove, axis=1)
#     return df


# column_to_remove = 'Unnamed: 0'
# df = remove_column(df, column_to_remove)

In [53]:
df

time  latitude  longitude        t2m       mx2t       mn2t  \
0      1981-01-01      27.5       87.5  272.44590  280.96375  264.93085   
1      1981-01-01      27.5       90.0  277.43057  280.59924  275.02722   
2      1981-01-01      27.5       92.5  273.97640  278.73110  269.32446   
3      1981-01-01      25.0       87.5  288.51346  294.98935  283.45917   
4      1981-01-01      25.0       90.0  289.99857  296.68546  285.48462   
...           ...       ...        ...        ...        ...        ...   
184075 2022-12-31      22.5       90.0  291.44186  296.95560  287.66700   
184076 2022-12-31      22.5       92.5  290.00693  296.92117  283.32626   
184077 2022-12-31      20.0       87.5  297.13577  297.48105  296.48117   
184078 2022-12-31      20.0       90.0  296.44460  296.68140  296.25607   
184079 2022-12-31      20.0       92.5  296.53552  296.92690  295.80237   

        rhum_1000hpa  rhum_850hpa  rhum_500hpa       u10  ...  geo_hgt_500hpa  \
0          71.980545    71.431860    58.090637 -0.194943  ...       56112.380   
1          91.592870    91.917410    43.649540 -0.027385  ...       56052.580   
2          78.709800    79.580480    61.536285  0.222168  ...       55991.418   
3          68.094640    34.034214     3.025867  2.514468  ...       56431.170   
4          62.741270    45.546825     3.685225  1.763424  ...       56328.844   
...              ...          ...          ...       ...  ...             ...   
184075     62.377167    35.078110     6.154188 -1.206016  ...       56989.902   
184076     68.681430    40.845684     4.719855 -0.077168  ...       56942.450   
184077     68.472150    39.682310     8.652951 -0.672088  ...       57410.918   
184078     61.102383    30.916985     6.653173 -1.102595  ...       57367.895   
184079     61.845367    32.810894     5.758938  1.753668  ...       57357.047   

        shum_1000hpa  shum_850hpa  shum_500hpa         msl         swvl1  \
0           0.004203     0.004203     0.001123  101491.630  3.795592e-01   
1           0.006046     0.006046     0.000922  101524.625  3.995494e-01   
2           0.004736     0.004673     0.001244  101638.680  3.902917e-01   
3           0.007803     0.003205     0.000099  101454.000  1.768660e-01   
4           0.008299     0.004048     0.000113  101371.190  1.641411e-01   
...              ...          ...          ...         ...           ...   
184075      0.008880     0.003838     0.000277  101785.970  2.226953e-01   
184076      0.008382     0.004143     0.000212  101778.900  2.116297e-01   
184077      0.011673     0.004990     0.000401  101705.970  5.948047e-07   
184078      0.009906     0.003796     0.000316  101741.695  5.948047e-07   
184079      0.009752     0.003920     0.000280  101702.305  5.948047e-07   

           swvl2  temp_1000hpa  temp_850hpa  temp_500hpa  
0       0.365721     293.15018    284.24010    260.50095  
1       0.393815     293.72390    284.79892    259.19534  
2       0.390833     292.92487    284.00497    258.53750  
3       0.199197     290.74564    283.99454    263.61220  
4       0.202003     291.92108    283.47208    262.94626  
...          ...           ...          ...          ...  
184075  0.257471     292.99512    286.31732    266.32822  
184076  0.239111     292.45758    285.81064    266.17575  
184077 -0.000004     295.60860    288.53555    266.92087  
184078 -0.000004     294.90536    288.11154    267.25967  
184079 -0.000004     294.53760    287.52988    267.34183  

[184080 rows x 25 columns]

In [54]:
df.set_index('time', inplace=True)


In [59]:

df_2021_april=df['2021-05-01':'2021-05-30']
df_2021_april['2021-05-23':'2021-05-25'][:]

latitude  longitude        t2m       mx2t       mn2t  \
time                                                               
2021-05-23      27.5       87.5  291.35532  293.60327  281.55652   
2021-05-23      27.5       90.0  290.72662  294.91998  283.27130   
2021-05-23      27.5       92.5  287.50330  291.21066  281.49774   
2021-05-23      25.0       87.5  305.55542  306.85706  299.19702   
2021-05-23      25.0       90.0  305.22717  307.13390  299.75882   
2021-05-23      25.0       92.5  303.34780  305.79694  296.78482   
2021-05-23      22.5       87.5  305.99190  309.44208  300.30252   
2021-05-23      22.5       90.0  305.83460  308.43036  300.27878   
2021-05-23      22.5       92.5  303.75180  311.20220  298.81723   
2021-05-23      20.0       87.5  303.17790  303.77686  302.23996   
2021-05-23      20.0       90.0  302.10960  303.08810  300.84960   
2021-05-23      20.0       92.5  302.05057  302.80900  300.99655   
2021-05-24      27.5       87.5  290.31506  292.94717  280.33008   
2021-05-24      27.5       90.0  290.10922  294.60600  282.79880   
2021-05-24      27.5       92.5  287.34872  291.61694  281.37115   
2021-05-24      25.0       87.5  305.04120  307.71120  300.76822   
2021-05-24      25.0       90.0  304.24942  308.18164  299.12015   
2021-05-24      25.0       92.5  303.21332  308.47650  298.41254   
2021-05-24      22.5       87.5  303.18417  308.73083  299.17667   
2021-05-24      22.5       90.0  303.59824  307.64484  299.70456   
2021-05-24      22.5       92.5  303.87076  309.17760  298.75390   
2021-05-24      20.0       87.5  301.63890  302.71335  300.84396   
2021-05-24      20.0       90.0  302.04840  303.02620  301.04742   
2021-05-24      20.0       92.5  301.48837  302.95080  300.84622   
2021-05-25      27.5       87.5  289.44397  293.13623  280.26114   
2021-05-25      27.5       90.0  287.81174  290.86630  283.51886   
2021-05-25      27.5       92.5  286.97360  287.42935  281.39603   
2021-05-25      25.0       87.5  300.21270  302.61768  297.27087   
2021-05-25      25.0       90.0  302.42755  305.11720  299.09753   
2021-05-25      25.0       92.5  303.10165  306.22570  298.72452   
2021-05-25      22.5       87.5  301.37170  304.18310  298.04858   
2021-05-25      22.5       90.0  301.71066  305.15770  299.47850   
2021-05-25      22.5       92.5  303.22223  308.22217  299.05460   
2021-05-25      20.0       87.5  301.81732  303.22766  300.73770   
2021-05-25      20.0       90.0  301.26224  302.74370  299.86960   
2021-05-25      20.0       92.5  301.63260  302.21030  300.84283   

            rhum_1000hpa  rhum_850hpa  rhum_500hpa        u10        v10  ...  \
time                                                                      ...   
2021-05-23     70.487785    70.779350    54.234330  -0.026508   0.445414  ...   
2021-05-23     76.655870    76.927810    50.328080  -0.118420   0.548184  ...   
2021-05-23     79.035645    79.128075    44.536210   0.123037   0.327704  ...   
2021-05-23     63.357174    77.374960    58.806880   0.033471  -0.587508  ...   
2021-05-23     72.627014    72.490400    29.557959  -0.276134  -0.383105  ...   
2021-05-23     69.312580    71.292210    41.504360  -0.196282  -0.631450  ...   
2021-05-23     65.886280    80.536800    45.615080  -0.065839  -0.858946  ...   
2021-05-23     69.569650    75.721470    65.455000  -0.517146   0.574459  ...   
2021-05-23     76.297966    83.018234    62.903667   0.142406   0.097225  ...   
2021-05-23     75.828860    68.525740    89.684880  -2.552925  -3.323228  ...   
2021-05-23     80.856970    81.254776    83.892830  -6.962223  -1.832388  ...   
2021-05-23     80.418220    81.646510    69.091850  -7.155199   5.591532  ...   
2021-05-24     70.087730    70.405450    70.575066  -0.005594  -0.006993  ...   
2021-05-24     73.667110    73.979780    77.320760  -0.141919   0.338299  ...   
2021-05-24     85.277560    85.547520    72.895680   0.094667   0.148553  ...   
2021-05-24     62.388016    74.619354    62.974216

In [7]:
# index_list=[0,184079,184078]

In [8]:
# date_mask=df['time'].isin(df['time'][index_list[:]])
# date_mask
# df_check=df[date_mask]
# df_check

# latitudes=df_check.loc[index_list,'latitude'].values
# latitudes

In [9]:
# condition = (df_check['mx2t'] > 295) & (df_check['mn2t'] > 290)
# indices = df_check.index[condition]
# indices

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 184080 entries, 1981-01-01 to 2022-12-31
Data columns (total 24 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   latitude         184080 non-null  float64
 1   longitude        184080 non-null  float64
 2   t2m              184080 non-null  float64
 3   mx2t             184080 non-null  float64
 4   mn2t             184080 non-null  float64
 5   rhum_1000hpa     184080 non-null  float64
 6   rhum_850hpa      184080 non-null  float64
 7   rhum_500hpa      184080 non-null  float64
 8   u10              184080 non-null  float64
 9   v10              184080 non-null  float64
 10  tp               184080 non-null  float64
 11  sp               184080 non-null  float64
 12  geo_hgt_1000hpa  184080 non-null  float64
 13  geo_hgt_850hpa   184080 non-null  float64
 14  geo_hgt_500hpa   184080 non-null  float64
 15  shum_1000hpa     184080 non-null  float64
 16  shum_850hpa      18408

In [45]:
df['mx2t'].describe(percentiles=[.5,.75,.90,.95])

count    184080.000000
mean        298.012698
std           7.555041
min         271.147160
50%         300.547850
75%         302.936170
90%         305.298710
95%         307.054055
max         317.076970
Name: mx2t, dtype: float64

In [46]:
df['mn2t'].describe(percentiles=[.5,.75,.90,.95])

count    184080.000000
mean        290.973538
std           9.519868
min         254.059330
50%         295.081370
75%         298.559327
90%         300.144642
95%         300.864264
max         305.554140
Name: mn2t, dtype: float64

In [47]:
df['t2m'].describe(percentiles=[.5,.75,.90,.95])

count    184080.000000
mean        294.782868
std           8.089371
min         263.745120
50%         297.955940
75%         300.913828
90%         302.190064
95%         302.935202
max         310.397550
Name: t2m, dtype: float64

In [13]:
lat_values=df.latitude.unique()
lon_values=df.longitude.unique()
dates=df.time.unique()

# HeatWave Detection - 1

In [14]:
from tqdm.auto import tqdm

duration = 0
index_list = []
HW_dates=[]

for lat in tqdm(lat_values, desc='Latitudes',leave=True):
    for lon in tqdm(lon_values, desc='Longitudes',leave=False):
        for date in tqdm(dates, desc='Dates', leave=False):
            date_mask = df['time'] == date
            lat_mask = df['latitude'] == lat
            lon_mask = df['longitude'] == lon
            
            if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() and (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
                duration += 1
                index_list.extend(df[date_mask & lat_mask & lon_mask].index)
#                 if duration >=3:
#                     df.loc[index_list,'Heatwave']=1
            else:               

                if duration>=3:
                    df.loc[index_list,'Heatwave']=1
                    HW_dates.append(df['time'][index_list[0]])
                    print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])

                    date_mask=df['time'].isin(df['time'][index_list[:]])
                    df_check=df[date_mask]
                    
                    if (df_check['mx2t'].values>=307.054055).any() or (df_check['mn2t'].values>=300.864264).any() :
                    
                        condition = (df_check['mx2t'] >=307.054055) | (df_check['mn2t'] >= 300.864264)
                        indices = df_check.index[condition]
                        df.loc[indices,'Heatwave']=1
                        latitudes=df_check.loc[indices,'latitude'].values
                        longitudes=df_check.loc[indices,'longitude'].values
                        for i, j in zip(latitudes, longitudes):
                            print('Surrounding Locations:')
                            print('Latitude:',i, '| Longitude:', j)


                duration = 0
                index_list = []                    
                        

Latitudes:   0%|          | 0/4 [00:00<?, ?it/s]

Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Duration: 8 days | Starting date: 1982-05-26 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latit

Duration: 4 days | Starting date: 1992-06-03 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 3 days | Starting date: 2009-06-21 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Duration: 3 days | Starting date: 2010-06-08 00:00:00 | lat: 25.0 lon: 87.5
Surround

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Duration: 3 days | Starting date: 1982-05-27 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 4 days | Starting date: 1984-05-15 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Duration: 5 days | Starting date: 1984-05-21 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surround

Duration: 5 days | Starting date: 1988-05-09 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 3 days | Starting date: 1995-05-06 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 3 days | Starting date: 1999-05-06 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Duration: 3 days | Starting date: 2000-04-30 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surround

Duration: 15 days | Starting date: 2004-05-09 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Lati

Duration: 7 days | Starting date: 2006-06-11 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latit

Duration: 4 days | Starting date: 2010-04-19 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 6 days | Starting date: 2011-05-13 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latit

Duration: 5 days | Starting date: 2013-05-21 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Duration: 3 days | Starting date: 2014-05-12 00:00:00 | lat: 22.5 lon: 87.5
Surround

Duration: 4 days | Starting date: 2016-05-14 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latit

Duration: 3 days | Starting date: 2019-05-22 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latit

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Duration: 5 days | Starting date: 1986-06-06 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 7 days | Starting date: 1999-05-01 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 4 days | Starting date: 2009-06-15 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latit

Duration: 4 days | Starting date: 2014-06-11 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latit

Duration: 6 days | Starting date: 2017-05-19 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 92.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 20.0 | Longitude: 90.0
Surrounding Locations:
Latitude: 20.0 | Longitude: 92.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latit

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

In [15]:
sanjid

NameError: name 'sanjid' is not defined

In [ ]:
# from tqdm.auto import tqdm

# duration = 0
# index_list = []
# HW_dates=[]

# for lat in tqdm(lat_values, desc='Latitudes',leave=True):
#     for lon in tqdm(lon_values, desc='Longitudes',leave=False):
#         for date in tqdm(dates, desc='Dates', leave=False):
#             date_mask = df['time'] == date
#             lat_mask = df['latitude'] == lat
#             lon_mask = df['longitude'] == lon
            
#             if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() and (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
#                 duration += 1
#                 index_list.extend(df[date_mask & lat_mask & lon_mask].index)
# #                 if duration >=3:
# #                     df.loc[index_list,'Heatwave']=1
#             else:               

#                 if duration>=3:
#                     df.loc[index_list,'Heatwave']=1
#                     HW_dates.append(df['time'][index_list[0]])
#                     print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])

#                     date_mask=df['time'].isin(df['time'][index_list[:]])
#                     df_check=df[date_mask]
                    
#                     if (df_check['mx2t'].values>=307.054055).any()and (df_check['mn2t'].values>=300.864264).any() :
                    
#                         condition = (df_check['mx2t'] >=307.054055) & (df_check['mn2t'] >= 300.864264)
#                         indices = df_check.index[condition]
#                         df.loc[indices,'Heatwave']=1
#                         latitudes=df_check.loc[condition,'latitude'].values
#                         longitudes=df_check.loc[condition,'longitude'].values
#                         for i, j in zip(latitudes, longitudes):
#                             print('Surrounding Locations:')
#                             print('Latitude:',i, '| Longitude:', j)


#                 duration = 0
#                 index_list = []                    
                        

Duration: 8 days | Starting date: 1982-05-26 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1982-07-04 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 1983-06-18 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 1985-05-30 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 1986-06-07 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 7 days | Starting date: 1987-06-25 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 1992-06-03 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Duration: 4 days | Starting date: 1995-05-29 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1995-06-14 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1997-06-07 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1998-05-21 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 2003-05-31 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2004-05-09 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2005-05-29 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 2005-06-10 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2009-06-21 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2010-06-08 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2012-05-19 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Duration: 3 days | Starting date: 2012-05-29 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 10 days | Starting date: 2012-06-07 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Duration: 7 days | Starting date: 2015-06-03 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 6 days | Starting date: 2019-06-13 00:00:00 | lat: 25.0 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1982-05-27 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1982-05-31 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 1982-07-03 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 26 days | Starting date: 1983-05-28 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 1984-05-15 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 1984-05-21 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1985-05-15 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 8 days | Starting date: 1985-05-27 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 1986-06-08 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 1987-05-29 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 20 days | Starting date: 1987-06-12 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 1988-05-09 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 7 days | Starting date: 1988-05-25 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 1990-05-25 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 9 days | Starting date: 1991-05-03 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1991-05-24 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1994-05-04 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 11 days | Starting date: 1994-05-29 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1995-05-06 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 7 days | Starting date: 1995-05-31 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 1995-06-15 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 13 days | Starting date: 1996-05-25 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 7 days | Starting date: 1997-06-05 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 24 days | Starting date: 1998-05-21 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 1999-05-06 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2000-04-30 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 2000-05-26 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2001-05-24 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2002-05-10 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2002-05-19 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2002-07-09 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 2003-05-25 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 14 days | Starting date: 2003-06-01 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 15 days | Starting date: 2004-05-09 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 30 days | Starting date: 2005-05-22 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 7 days | Starting date: 2006-06-11 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 2007-05-23 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 2007-05-30 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 2007-06-05 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 2008-05-30 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 13 days | Starting date: 2009-06-12 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 2010-04-19 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 2010-04-30 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 7 days | Starting date: 2010-05-10 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 17 days | Starting date: 2010-05-26 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 2011-05-13 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 2011-05-21 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 2012-05-14 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 25 days | Starting date: 2012-05-22 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 2012-06-26 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 2013-05-21 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2014-05-12 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 12 days | Starting date: 2014-06-05 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 16 days | Starting date: 2015-05-21 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2015-06-07 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 4 days | Starting date: 2016-05-14 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 12 days | Starting date: 2017-05-15 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 2017-06-01 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 2018-06-15 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2019-05-22 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2019-05-27 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 6 days | Starting date: 2019-06-14 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2021-05-18 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2021-06-05 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 3 days | Starting date: 2022-05-14 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 14 days | Starting date: 2022-06-01 00:00:00 | lat: 22.5 lon: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Duration: 5 days | Starting date: 1986-06-06 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 1987-06-14 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 1994-05-04 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 1995-05-01 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 1996-05-25 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 1998-05-29 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 7 days | Starting date: 1998-06-04 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 7 days | Starting date: 1999-05-01 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2003-05-26 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 2004-05-11 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2005-05-24 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 2005-06-01 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2005-06-08 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2005-06-16 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 2009-06-15 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2009-06-21 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2010-04-20 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2010-05-09 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2010-06-07 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2012-05-13 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2012-05-23 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 2012-06-03 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 4 days | Starting date: 2014-06-11 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 12 days | Starting date: 2015-05-22 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2015-06-08 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 25.0 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 5 days | Starting date: 2016-04-22 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 6 days | Starting date: 2017-05-19 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 6 days | Starting date: 2018-06-14 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Duration: 3 days | Starting date: 2019-05-30 00:00:00 | lat: 22.5 lon: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
Surrounding Locations:
Latitude: 22.5 | Longitude: 87.5
Surrounding Locations:
Latitude: 22.5 | Longitude: 90.0
sanjid


In [ ]:
sanjid

In [ ]:
import pandas as pd
import numpy as np

# Generate random data
np.random.seed(0)
data = {
    'tmax': np.random.randint(290, 310, 10),  # Random tmax values between 290 and 310 K
    'tmin': np.random.randint(270, 280, 10),  # Random tmin values between 270 and 280 K
}

# Create DataFrame
df = pd.DataFrame(data)

# Initialize 'heatwave' column with zeros
df['heatwave'] = 0

# Define the conditions
condition = (df['tmax'] > 300) & (df['tmin'] > 273)

# Assign 1 to the 'heatwave' column where conditions are met
df.loc[condition, 'heatwave'] = 1

# Print the resulting DataFrame
print(df)



In [ ]:
import pandas as pd
import numpy as np

# Generate random data
np.random.seed(0)
data = {
    'tmax': np.random.randint(290, 310, 10),  # Random tmax values between 290 and 310 K
    'tmin': np.random.randint(270, 280, 10),  # Random tmin values between 270 and 280 K
}

# Create DataFrame
df = pd.DataFrame(data)

# Define the conditions
condition = (df['tmax'] > 300) & (df['tmin'] > 273)

# Get the indices where conditions are met
indices = df.index[condition].tolist()

# Print the indices
print(indices)


In [ ]:
# from tqdm.auto import tqdm

# duration = 0
# index_list = []
# HW_dates=[]

# for lat in tqdm(lat_values, desc='Latitudes',leave=True):
#     for lon in tqdm(lon_values, desc='Longitudes',leave=False):
#         for date in tqdm(dates, desc='Dates', leave=False):
#             date_mask = df['time'] == date
#             lat_mask = df['latitude'] == lat
#             lon_mask = df['longitude'] == lon
            
#             if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() and (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
#                 duration += 1
#                 index_list.extend(df[date_mask & lat_mask & lon_mask].index)
# #                 if duration >=3:
# #                     df.loc[index_list,'Heatwave']=1
#             else:               

#                 if duration>=3:
#                     df.loc[index_list,'Heatwave']=1
#                     HW_dates.append(df['time'][index_list[0]])

#                     print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])

#                 duration = 0
#                 index_list = []
            



In [ ]:
# to add a list to a list use extend
# to add an elemnet to a list use append

In [ ]:
HW_dates

In [ ]:
df.to_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/Basic_heatwave.csv',index=False)

In [ ]:
# sanjid

In [ ]:
# from tqdm.auto import tqdm

# duration = 0
# index_list = []

# for lat in tqdm(lat_values, desc='Latitudes',leave=True):
#     for lon in tqdm(lon_values, desc='Longitudes',leave=False):
#         for date in tqdm(dates, desc='Dates', leave=False):
#             date_mask = df['time'] == date
#             lat_mask = df['latitude'] == lat
#             lon_mask = df['longitude'] == lon
            
#             if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() and (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
#                 duration += 1
#                 index_list.extend(df[date_mask & lat_mask & lon_mask].index)
# #                 if duration >=3:
# #                     df.loc[index_list,'Heatwave']=1
#             else:
#                 if duration == 1:
                
#                     date_mask=df['time']==df['time'][index_list[0]]
#                     df_check=df[date_mask]
# #                     if (df_check[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any():
#                     if (df_check['Heatwave'].values==1).any():
#                         df.loc[index_list,'Heatwave']=1
#                         print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])
                        
#                 if duration==2:
#                     date_mask1=df['time']==df['time'][index_list[0]]
#                     date_mask2=df['time']==df['time'][index_list[1]]
#                     df_check1=df[date_mask1]
#                     df_check2=df[date_mask2]
#                     if (df_check1['Heatwave'].values==1).any() or (df_check2['Heatwave'].values==1).any():
#                         df.loc[index_list,'Heatwave']=1                
#                         print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])
#                 if duration>=3:
#                     print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])
                    
#                 duration = 0
#                 index_list = []
            



In [ ]:
# using tmax or tmin

In [ ]:
df=pd.read_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/Basic_heatwave.csv')

In [ ]:
from tqdm.auto import tqdm

duration = 0
index_list = []

for lat in tqdm(lat_values, desc='Latitudes',leave=True):
    for lon in tqdm(lon_values, desc='Longitudes',leave=False):
        for date in tqdm(dates, desc='Dates', leave=False):
            date_mask = df['time'] == date
            lat_mask = df['latitude'] == lat
            lon_mask = df['longitude'] == lon
            
            if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() or (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
                duration += 1
                index_list.extend(df[date_mask & lat_mask & lon_mask].index)
            else:
                if duration >= 1:
                    date_mask=df['time'].isin(df['time'][index_list[:]])
                    df_check=df[date_mask]
                    if (df_check['Heatwave'].values==1).any():
                        df.loc[index_list,'Heatwave']=1
                        print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])
                duration = 0
                index_list = []                    
                        

Duration: 19 days | Starting date: 1982-05-15 | lat: 25.0 lon: 87.5
Duration: 8 days | Starting date: 1982-07-02 | lat: 25.0 lon: 87.5
Duration: 13 days | Starting date: 1983-05-27 | lat: 25.0 lon: 87.5
Duration: 13 days | Starting date: 1983-06-10 | lat: 25.0 lon: 87.5
Duration: 7 days | Starting date: 1984-05-17 | lat: 25.0 lon: 87.5
Duration: 5 days | Starting date: 1985-05-15 | lat: 25.0 lon: 87.5
Duration: 10 days | Starting date: 1985-05-26 | lat: 25.0 lon: 87.5
Duration: 15 days | Starting date: 1986-05-28 | lat: 25.0 lon: 87.5
Duration: 23 days | Starting date: 1987-05-10 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 1987-06-12 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 1987-06-17 | lat: 25.0 lon: 87.5
Duration: 9 days | Starting date: 1987-06-24 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 1988-05-08 | lat: 25.0 lon: 87.5
Duration: 8 days | Starting date: 1988-05-22 | lat: 25.0 lon: 87.5
Duration: 16 days | Starting date: 1991-04-29 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 1991-05-22 | lat: 25.0 lon: 87.5
Duration: 9 days | Starting date: 1992-05-30 | lat: 25.0 lon: 87.5
Duration: 16 days | Starting date: 1994-04-23 | lat: 25.0 lon: 87.5
Duration: 5 days | Starting date: 1994-05-28 | lat: 25.0 lon: 87.5
Duration: 1 days | Starting date: 1994-06-03 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 1994-06-06 | lat: 25.0 lon: 87.5
Duration: 46 days | Starting date: 1995-03-29 | lat: 25.0 lon: 87.5
Duration: 16 days | Starting date: 1995-05-18 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 1995-06-14 | lat: 25.0 lon: 87.5
Duration: 16 days | Starting date: 1996-05-16 | lat: 25.0 lon: 87.5
Duration: 12 days | Starting date: 1997-06-01 | lat: 25.0 lon: 87.5
Duration: 7 days | Starting date: 1998-05-18 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 1998-05-30 | lat: 25.0 lon: 87.5
Duration: 9 days | Starting date: 1998-06-06 | lat: 25.0 lon: 87.5
Duration: 22 days | Starting date: 1999-04-14 | lat: 25.0 lon: 87.5
Duration: 1 days | Starting date: 1999-05-08 | lat: 25.0 lon: 87.5
Duration: 1 days | Starting date: 2000-05-01 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 2000-05-26 | lat: 25.0 lon: 87.5
Duration: 2 days | Starting date: 2001-05-23 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 2002-05-20 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 2002-07-10 | lat: 25.0 lon: 87.5
Duration: 13 days | Starting date: 2003-05-24 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 2003-06-12 | lat: 25.0 lon: 87.5
Duration: 21 days | Starting date: 2004-05-01 | lat: 25.0 lon: 87.5
Duration: 22 days | Starting date: 2005-05-25 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 2005-06-17 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 2006-06-11 | lat: 25.0 lon: 87.5
Duration: 14 days | Starting date: 2007-05-21 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 2008-05-28 | lat: 25.0 lon: 87.5
Duration: 5 days | Starting date: 2009-06-08 | lat: 25.0 lon: 87.5
Duration: 11 days | Starting date: 2009-06-14 | lat: 25.0 lon: 87.5
Duration: 8 days | Starting date: 2010-04-19 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 2010-05-02 | lat: 25.0 lon: 87.5
Duration: 8 days | Starting date: 2010-05-09 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 2010-05-31 | lat: 25.0 lon: 87.5
Duration: 12 days | Starting date: 2010-06-05 | lat: 25.0 lon: 87.5
Duration: 2 days | Starting date: 2011-05-14 | lat: 25.0 lon: 87.5
Duration: 2 days | Starting date: 2011-05-23 | lat: 25.0 lon: 87.5
Duration: 21 days | Starting date: 2012-05-06 | lat: 25.0 lon: 87.5
Duration: 21 days | Starting date: 2012-05-28 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 2012-06-25 | lat: 25.0 lon: 87.5
Duration: 20 days | Starting date: 2014-05-06 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 2014-06-04 | lat: 25.0 lon: 87.5
Duration: 9 days | Starting date: 2014-06-09 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 2015-05-21 | lat: 25.0 lon: 87.5
Duration: 1 days | Starting date: 2015-05-27 | lat: 25.0 lon: 87.5
Duration: 11 days | Starting date: 2015-05-31 | lat: 25.0 lon: 87.5
Duration: 13 days | Starting date: 2016-04-19 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 2016-05-15 | lat: 25.0 lon: 87.5
Duration: 7 days | Starting date: 2017-05-19 | lat: 25.0 lon: 87.5
Duration: 4 days | Starting date: 2017-06-01 | lat: 25.0 lon: 87.5
Duration: 2 days | Starting date: 2018-06-14 | lat: 25.0 lon: 87.5
Duration: 3 days | Starting date: 2018-06-17 | lat: 25.0 lon: 87.5
Duration: 7 days | Starting date: 2019-05-17 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 2019-05-25 | lat: 25.0 lon: 87.5
Duration: 12 days | Starting date: 2019-06-08 | lat: 25.0 lon: 87.5
Duration: 1 days | Starting date: 2021-05-20 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 2021-06-03 | lat: 25.0 lon: 87.5
Duration: 7 days | Starting date: 2022-05-13 | lat: 25.0 lon: 87.5
Duration: 2 days | Starting date: 2022-06-03 | lat: 25.0 lon: 87.5
Duration: 8 days | Starting date: 2022-06-08 | lat: 25.0 lon: 87.5
Duration: 6 days | Starting date: 1982-05-21 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1982-07-03 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1983-05-31 | lat: 25.0 lon: 90.0
Duration: 3 days | Starting date: 1983-06-06 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1984-05-19 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1986-06-01 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1986-06-03 | lat: 25.0 lon: 90.0
Duration: 4 days | Starting date: 1986-06-05 | lat: 25.0 lon: 90.0
Duration: 7 days | Starting date: 1987-05-14 | lat: 25.0 lon: 90.0
Duration: 7 days | Starting date: 1987-05-23 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 1987-06-17 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1988-05-10 | lat: 25.0 lon: 90.0
Duration: 3 days | Starting date: 1992-05-31 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1992-06-05 | lat: 25.0 lon: 90.0
Duration: 7 days | Starting date: 1994-05-02 | lat: 25.0 lon: 90.0
Duration: 7 days | Starting date: 1995-04-01 | lat: 25.0 lon: 90.0
Duration: 3 days | Starting date: 1995-04-12 | lat: 25.0 lon: 90.0
Duration: 13 days | Starting date: 1995-04-16 | lat: 25.0 lon: 90.0
Duration: 7 days | Starting date: 1995-04-30 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1995-05-11 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1995-05-13 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 1995-05-18 | lat: 25.0 lon: 90.0
Duration: 8 days | Starting date: 1995-05-21 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1996-05-28 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1997-06-02 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 1998-05-19 | lat: 25.0 lon: 90.0
Duration: 5 days | Starting date: 1998-06-06 | lat: 25.0 lon: 90.0
Duration: 8 days | Starting date: 1999-04-24 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1999-05-03 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2002-05-20 | lat: 25.0 lon: 90.0
Duration: 4 days | Starting date: 2003-05-26 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2003-06-03 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2004-05-06 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2004-05-08 | lat: 25.0 lon: 90.0
Duration: 5 days | Starting date: 2004-05-10 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2004-05-17 | lat: 25.0 lon: 90.0
Duration: 6 days | Starting date: 2005-05-28 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2005-06-10 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2006-06-11 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2007-05-23 | lat: 25.0 lon: 90.0
Duration: 4 days | Starting date: 2007-05-30 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2008-05-29 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2009-06-08 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2009-06-17 | lat: 25.0 lon: 90.0
Duration: 4 days | Starting date: 2010-04-20 | lat: 25.0 lon: 90.0
Duration: 4 days | Starting date: 2010-05-11 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2010-06-07 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2012-05-14 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2012-05-23 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2012-06-03 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2014-05-09 | lat: 25.0 lon: 90.0
Duration: 4 days | Starting date: 2014-05-13 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2014-05-18 | lat: 25.0 lon: 90.0
Duration: 3 days | Starting date: 2014-05-21 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2014-06-15 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2015-05-22 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2016-04-21 | lat: 25.0 lon: 90.0
Duration: 3 days | Starting date: 2016-04-23 | lat: 25.0 lon: 90.0
Duration: 3 days | Starting date: 2016-04-28 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2019-05-18 | lat: 25.0 lon: 90.0
Duration: 3 days | Starting date: 2019-06-12 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 2019-06-16 | lat: 25.0 lon: 90.0
Duration: 2 days | Starting date: 2019-06-19 | lat: 25.0 lon: 90.0
Duration: 1 days | Starting date: 1999-04-14 | lat: 25.0 lon: 92.5
Duration: 42 days | Starting date: 1982-04-22 | lat: 22.5 lon: 87.5
Duration: 16 days | Starting date: 1982-06-24 | lat: 22.5 lon: 87.5
Duration: 36 days | Starting date: 1983-05-19 | lat: 22.5 lon: 87.5
Duration: 33 days | Starting date: 1984-04-24 | lat: 22.5 lon: 87.5
Duration: 15 days | Starting date: 1985-05-09 | lat: 22.5 lon: 87.5
Duration: 11 days | Starting date: 1985-05-25 | lat: 22.5 lon: 87.5
Duration: 29 days | Starting date: 1986-05-17 | lat: 22.5 lon: 87.5
Duration: 30 days | Starting date: 1987-05-10 | lat: 22.5 lon: 87.5
Duration: 23 days | Starting date: 1987-06-10 | lat: 22.5 lon: 87.5
Duration: 15 days | Starting date: 1988-05-02 | lat: 22.5 lon: 87.5
Duration: 17 days | Starting date: 1988-05-22 | lat: 22.5 lon: 87.5
Duration: 14 days | Starting date: 1990-05-20 | lat: 22.5 lon: 87.5
Duration: 32 days | Starting date: 1991-04-30 | lat: 22.5 lon: 87.5
Duration: 12 days | Starting date: 1992-05-29 | lat: 22.5 lon: 87.5
Duration: 6 days | Starting date: 1994-04-24 | lat: 22.5 lon: 87.5
Duration: 19 days | Starting date: 1994-05-01 | lat: 22.5 lon: 87.5
Duration: 13 days | Starting date: 1994-05-27 | lat: 22.5 lon: 87.5
Duration: 42 days | Starting date: 1995-03-29 | lat: 22.5 lon: 87.5
Duration: 22 days | Starting date: 1995-05-18 | lat: 22.5 lon: 87.5
Duration: 6 days | Starting date: 1995-06-14 | lat: 22.5 lon: 87.5
Duration: 38 days | Starting date: 1996-05-01 | lat: 22.5 lon: 87.5
Duration: 42 days | Starting date: 1997-05-02 | lat: 22.5 lon: 87.5
Duration: 26 days | Starting date: 1998-05-19 | lat: 22.5 lon: 87.5
Duration: 56 days | Starting date: 1999-03-16 | lat: 22.5 lon: 87.5
Duration: 5 days | Starting date: 2000-04-28 | lat: 22.5 lon: 87.5
Duration: 11 days | Starting date: 2000-05-25 | lat: 22.5 lon: 87.5
Duration: 11 days | Starting date: 2001-05-17 | lat: 22.5 lon: 87.5
Duration: 31 days | Starting date: 2002-04-14 | lat: 22.5 lon: 87.5
Duration: 11 days | Starting date: 2002-05-18 | lat: 22.5 lon: 87.5
Duration: 8 days | Starting date: 2002-07-07 | lat: 22.5 lon: 87.5
Duration: 35 days | Starting date: 2003-05-11 | lat: 22.5 lon: 87.5
Duration: 40 days | Starting date: 2004-04-27 | lat: 22.5 lon: 87.5
Duration: 53 days | Starting date: 2005-05-03 | lat: 22.5 lon: 87.5
Duration: 10 days | Starting date: 2006-06-11 | lat: 22.5 lon: 87.5
Duration: 21 days | Starting date: 2007-05-21 | lat: 22.5 lon: 87.5
Duration: 57 days | Starting date: 2008-04-09 | lat: 22.5 lon: 87.5
Duration: 19 days | Starting date: 2009-06-07 | lat: 22.5 lon: 87.5
Duration: 70 days | Starting date: 2010-03-12 | lat: 22.5 lon: 87.5
Duration: 18 days | Starting date: 2010-05-25 | lat: 22.5 lon: 87.5
Duration: 4 days | Starting date: 2010-06-15 | lat: 22.5 lon: 87.5
Duration: 19 days | Starting date: 2011-05-07 | lat: 22.5 lon: 87.5
Duration: 44 days | Starting date: 2012-05-06 | lat: 22.5 lon: 87.5
Duration: 6 days | Starting date: 2012-06-25 | lat: 22.5 lon: 87.5
Duration: 10 days | Starting date: 2013-05-17 | lat: 22.5 lon: 87.5
Duration: 60 days | Starting date: 2014-03-26 | lat: 22.5 lon: 87.5
Duration: 14 days | Starting date: 2014-06-04 | lat: 22.5 lon: 87.5
Duration: 26 days | Starting date: 2015-05-18 | lat: 22.5 lon: 87.5
Duration: 49 days | Starting date: 2016-03-31 | lat: 22.5 lon: 87.5
Duration: 80 days | Starting date: 2017-03-22 | lat: 22.5 lon: 87.5
Duration: 13 days | Starting date: 2018-06-10 | lat: 22.5 lon: 87.5
Duration: 28 days | Starting date: 2019-05-05 | lat: 22.5 lon: 87.5
Duration: 12 days | Starting date: 2019-06-09 | lat: 22.5 lon: 87.5
Duration: 11 days | Starting date: 2021-05-14 | lat: 22.5 lon: 87.5
Duration: 8 days | Starting date: 2021-06-01 | lat: 22.5 lon: 87.5
Duration: 11 days | Starting date: 2022-05-13 | lat: 22.5 lon: 87.5
Duration: 23 days | Starting date: 2022-05-25 | lat: 22.5 lon: 87.5
Duration: 2 days | Starting date: 1982-04-30 | lat: 22.5 lon: 90.0
Duration: 10 days | Starting date: 1982-05-03 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1982-05-14 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1982-05-16 | lat: 22.5 lon: 90.0
Duration: 15 days | Starting date: 1982-05-18 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 1982-07-03 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1983-05-28 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 1983-06-06 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 1984-04-26 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 1984-05-02 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1984-05-19 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1984-05-21 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 1985-05-17 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1985-05-28 | lat: 22.5 lon: 90.0
Duration: 5 days | Starting date: 1986-05-22 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1986-05-29 | lat: 22.5 lon: 90.0
Duration: 10 days | Starting date: 1986-06-02 | lat: 22.5 lon: 90.0
Duration: 23 days | Starting date: 1987-05-11 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1987-06-06 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1987-06-12 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1987-06-14 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1987-06-26 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1987-06-30 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 1988-05-10 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1988-05-26 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1988-06-06 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1990-05-24 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 1991-05-08 | lat: 22.5 lon: 90.0
Duration: 8 days | Starting date: 1992-05-31 | lat: 22.5 lon: 90.0
Duration: 6 days | Starting date: 1994-05-03 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1994-05-12 | lat: 22.5 lon: 90.0
Duration: 8 days | Starting date: 1994-05-29 | lat: 22.5 lon: 90.0
Duration: 29 days | Starting date: 1995-03-17 | lat: 22.5 lon: 90.0
Duration: 23 days | Starting date: 1995-04-17 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1995-05-18 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1995-05-27 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1995-06-16 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 1996-05-09 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1996-05-14 | lat: 22.5 lon: 90.0
Duration: 13 days | Starting date: 1996-05-17 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1997-05-15 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 1997-05-20 | lat: 22.5 lon: 90.0
Duration: 5 days | Starting date: 1997-06-04 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1998-05-21 | lat: 22.5 lon: 90.0
Duration: 14 days | Starting date: 1998-05-29 | lat: 22.5 lon: 90.0
Duration: 8 days | Starting date: 1999-03-17 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 1999-03-27 | lat: 22.5 lon: 90.0
Duration: 7 days | Starting date: 1999-04-01 | lat: 22.5 lon: 90.0
Duration: 25 days | Starting date: 1999-04-14 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2000-05-27 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2002-04-22 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2002-04-25 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2002-04-28 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 2002-05-01 | lat: 22.5 lon: 90.0
Duration: 5 days | Starting date: 2002-05-19 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2002-07-09 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2002-07-12 | lat: 22.5 lon: 90.0
Duration: 6 days | Starting date: 2003-05-08 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2003-05-19 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2003-05-22 | lat: 22.5 lon: 90.0
Duration: 11 days | Starting date: 2003-05-24 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2003-06-06 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2003-06-09 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 2003-06-11 | lat: 22.5 lon: 90.0
Duration: 12 days | Starting date: 2004-05-03 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2004-05-20 | lat: 22.5 lon: 90.0
Duration: 7 days | Starting date: 2005-05-10 | lat: 22.5 lon: 90.0
Duration: 13 days | Starting date: 2005-05-24 | lat: 22.5 lon: 90.0
Duration: 6 days | Starting date: 2005-06-08 | lat: 22.5 lon: 90.0
Duration: 5 days | Starting date: 2005-06-15 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2006-06-12 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2007-05-23 | lat: 22.5 lon: 90.0
Duration: 8 days | Starting date: 2007-05-26 | lat: 22.5 lon: 90.0
Duration: 7 days | Starting date: 2008-04-09 | lat: 22.5 lon: 90.0
Duration: 19 days | Starting date: 2008-04-17 | lat: 22.5 lon: 90.0
Duration: 6 days | Starting date: 2008-05-10 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 2008-05-17 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2008-05-22 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 2008-05-28 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2009-06-08 | lat: 22.5 lon: 90.0
Duration: 11 days | Starting date: 2009-06-13 | lat: 22.5 lon: 90.0
Duration: 14 days | Starting date: 2010-03-11 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2010-03-26 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2010-04-01 | lat: 22.5 lon: 90.0
Duration: 25 days | Starting date: 2010-04-03 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2010-04-30 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 2010-05-02 | lat: 22.5 lon: 90.0
Duration: 12 days | Starting date: 2010-05-09 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2010-05-27 | lat: 22.5 lon: 90.0
Duration: 11 days | Starting date: 2010-05-31 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 2011-05-10 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 2011-05-15 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2011-05-22 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2012-05-07 | lat: 22.5 lon: 90.0
Duration: 8 days | Starting date: 2012-05-12 | lat: 22.5 lon: 90.0
Duration: 7 days | Starting date: 2012-05-21 | lat: 22.5 lon: 90.0
Duration: 10 days | Starting date: 2012-06-03 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2012-06-14 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2012-06-28 | lat: 22.5 lon: 90.0
Duration: 7 days | Starting date: 2014-03-28 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2014-04-05 | lat: 22.5 lon: 90.0
Duration: 24 days | Starting date: 2014-04-09 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2014-05-04 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 2014-05-07 | lat: 22.5 lon: 90.0
Duration: 12 days | Starting date: 2014-05-12 | lat: 22.5 lon: 90.0
Duration: 9 days | Starting date: 2014-06-09 | lat: 22.5 lon: 90.0
Duration: 22 days | Starting date: 2015-05-21 | lat: 22.5 lon: 90.0
Duration: 9 days | Starting date: 2016-04-07 | lat: 22.5 lon: 90.0
Duration: 13 days | Starting date: 2016-04-19 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2016-05-06 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 2016-05-10 | lat: 22.5 lon: 90.0
Duration: 4 days | Starting date: 2016-05-15 | lat: 22.5 lon: 90.0
Duration: 5 days | Starting date: 2017-04-10 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2017-04-17 | lat: 22.5 lon: 90.0
Duration: 3 days | Starting date: 2017-05-04 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2017-05-08 | lat: 22.5 lon: 90.0
Duration: 5 days | Starting date: 2017-05-11 | lat: 22.5 lon: 90.0
Duration: 12 days | Starting date: 2017-05-18 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2017-06-03 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2017-06-07 | lat: 22.5 lon: 90.0
Duration: 6 days | Starting date: 2018-06-14 | lat: 22.5 lon: 90.0
Duration: 8 days | Starting date: 2019-05-06 | lat: 22.5 lon: 90.0
Duration: 6 days | Starting date: 2019-05-17 | lat: 22.5 lon: 90.0
Duration: 9 days | Starting date: 2019-05-24 | lat: 22.5 lon: 90.0
Duration: 8 days | Starting date: 2019-06-12 | lat: 22.5 lon: 90.0
Duration: 6 days | Starting date: 2021-05-15 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2021-05-23 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2022-05-15 | lat: 22.5 lon: 90.0
Duration: 1 days | Starting date: 2022-05-18 | lat: 22.5 lon: 90.0
Duration: 2 days | Starting date: 2022-06-13 | lat: 22.5 lon: 90.0
Duration: 11 days | Starting date: 1982-05-04 | lat: 22.5 lon: 92.5
Duration: 10 days | Starting date: 1982-05-16 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 1982-05-28 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 1983-05-26 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1983-05-30 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 1985-05-08 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 1985-05-16 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1986-05-17 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1986-05-19 | lat: 22.5 lon: 92.5
Duration: 9 days | Starting date: 1986-05-21 | lat: 22.5 lon: 92.5
Duration: 6 days | Starting date: 1986-06-03 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 1986-06-11 | lat: 22.5 lon: 92.5
Duration: 22 days | Starting date: 1987-05-11 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1987-06-15 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 1988-05-02 | lat: 22.5 lon: 92.5
Duration: 11 days | Starting date: 1988-05-06 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1990-05-23 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1992-06-02 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 1992-06-04 | lat: 22.5 lon: 92.5
Duration: 4 days | Starting date: 1994-04-27 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 1994-05-13 | lat: 22.5 lon: 92.5
Duration: 10 days | Starting date: 1995-03-18 | lat: 22.5 lon: 92.5
Duration: 8 days | Starting date: 1995-04-01 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 1995-04-10 | lat: 22.5 lon: 92.5
Duration: 15 days | Starting date: 1995-04-16 | lat: 22.5 lon: 92.5
Duration: 8 days | Starting date: 1995-05-02 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1995-05-13 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1995-05-19 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 1995-05-25 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 1996-05-20 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 1997-05-09 | lat: 22.5 lon: 92.5
Duration: 4 days | Starting date: 1997-05-14 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 1998-05-17 | lat: 22.5 lon: 92.5
Duration: 6 days | Starting date: 1999-03-20 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 1999-03-30 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 1999-04-02 | lat: 22.5 lon: 92.5
Duration: 27 days | Starting date: 1999-04-09 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1999-05-09 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2000-04-29 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2000-05-02 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 2002-04-12 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2002-04-16 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 2002-04-18 | lat: 22.5 lon: 92.5
Duration: 11 days | Starting date: 2002-04-24 | lat: 22.5 lon: 92.5
Duration: 7 days | Starting date: 2003-05-07 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 2003-05-29 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2004-05-01 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 2004-05-03 | lat: 22.5 lon: 92.5
Duration: 4 days | Starting date: 2004-05-07 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2004-05-13 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2004-05-16 | lat: 22.5 lon: 92.5
Duration: 11 days | Starting date: 2005-05-11 | lat: 22.5 lon: 92.5
Duration: 10 days | Starting date: 2005-05-27 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 2005-06-08 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2005-06-13 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2005-06-16 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2007-06-02 | lat: 22.5 lon: 92.5
Duration: 39 days | Starting date: 2008-04-05 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2008-05-19 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2009-06-17 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 2010-03-09 | lat: 22.5 lon: 92.5
Duration: 15 days | Starting date: 2010-03-14 | lat: 22.5 lon: 92.5
Duration: 12 days | Starting date: 2010-04-06 | lat: 22.5 lon: 92.5
Duration: 6 days | Starting date: 2010-04-22 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 2010-04-30 | lat: 22.5 lon: 92.5
Duration: 14 days | Starting date: 2010-05-06 | lat: 22.5 lon: 92.5
Duration: 8 days | Starting date: 2011-05-09 | lat: 22.5 lon: 92.5
Duration: 4 days | Starting date: 2012-05-05 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2012-05-14 | lat: 22.5 lon: 92.5
Duration: 4 days | Starting date: 2012-05-17 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 2012-05-23 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2012-06-07 | lat: 22.5 lon: 92.5
Duration: 9 days | Starting date: 2014-03-27 | lat: 22.5 lon: 92.5
Duration: 27 days | Starting date: 2014-04-08 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2014-05-06 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2014-05-14 | lat: 22.5 lon: 92.5
Duration: 7 days | Starting date: 2014-05-16 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2014-05-25 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2014-06-07 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2014-06-09 | lat: 22.5 lon: 92.5
Duration: 3 days | Starting date: 2014-06-12 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2015-05-21 | lat: 22.5 lon: 92.5
Duration: 6 days | Starting date: 2015-05-25 | lat: 22.5 lon: 92.5
Duration: 4 days | Starting date: 2015-06-02 | lat: 22.5 lon: 92.5
Duration: 15 days | Starting date: 2016-04-07 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2016-04-23 | lat: 22.5 lon: 92.5
Duration: 6 days | Starting date: 2016-04-27 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 2016-05-08 | lat: 22.5 lon: 92.5
Duration: 5 days | Starting date: 2016-05-14 | lat: 22.5 lon: 92.5
Duration: 8 days | Starting date: 2017-04-08 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2017-04-17 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2017-04-20 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2017-04-29 | lat: 22.5 lon: 92.5
Duration: 14 days | Starting date: 2017-05-01 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2017-05-16 | lat: 22.5 lon: 92.5
Duration: 10 days | Starting date: 2017-05-19 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 2017-06-07 | lat: 22.5 lon: 92.5
Duration: 11 days | Starting date: 2019-05-05 | lat: 22.5 lon: 92.5
Duration: 6 days | Starting date: 2019-05-18 | lat: 22.5 lon: 92.5
Duration: 8 days | Starting date: 2019-05-26 | lat: 22.5 lon: 92.5
Duration: 2 days | Starting date: 2019-06-17 | lat: 22.5 lon: 92.5
Duration: 11 days | Starting date: 2021-05-15 | lat: 22.5 lon: 92.5
Duration: 1 days | Starting date: 1982-04-30 | lat: 20.0 lon: 87.5
Duration: 25 days | Starting date: 1982-05-09 | lat: 20.0 lon: 87.5
Duration: 15 days | Starting date: 1982-06-25 | lat: 20.0 lon: 87.5
Duration: 12 days | Starting date: 1983-05-13 | lat: 20.0 lon: 87.5
Duration: 9 days | Starting date: 1983-05-26 | lat: 20.0 lon: 87.5
Duration: 7 days | Starting date: 1983-06-05 | lat: 20.0 lon: 87.5
Duration: 11 days | Starting date: 1983-06-13 | lat: 20.0 lon: 87.5
Duration: 31 days | Starting date: 1984-04-26 | lat: 20.0 lon: 87.5
Duration: 13 days | Starting date: 1985-05-08 | lat: 20.0 lon: 87.5
Duration: 10 days | Starting date: 1985-05-25 | lat: 20.0 lon: 87.5
Duration: 36 days | Starting date: 1986-05-10 | lat: 20.0 lon: 87.5
Duration: 32 days | Starting date: 1987-05-10 | lat: 20.0 lon: 87.5
Duration: 4 days | Starting date: 1987-06-12 | lat: 20.0 lon: 87.5
Duration: 18 days | Starting date: 1987-06-17 | lat: 20.0 lon: 87.5
Duration: 14 days | Starting date: 1988-05-05 | lat: 20.0 lon: 87.5
Duration: 17 days | Starting date: 1988-05-22 | lat: 20.0 lon: 87.5
Duration: 18 days | Starting date: 1990-05-16 | lat: 20.0 lon: 87.5
Duration: 32 days | Starting date: 1991-04-30 | lat: 20.0 lon: 87.5
Duration: 18 days | Starting date: 1992-05-29 | lat: 20.0 lon: 87.5
Duration: 6 days | Starting date: 1994-04-19 | lat: 20.0 lon: 87.5
Duration: 24 days | Starting date: 1994-04-27 | lat: 20.0 lon: 87.5
Duration: 17 days | Starting date: 1994-05-24 | lat: 20.0 lon: 87.5
Duration: 1 days | Starting date: 1995-03-24 | lat: 20.0 lon: 87.5
Duration: 3 days | Starting date: 1995-03-28 | lat: 20.0 lon: 87.5
Duration: 31 days | Starting date: 1995-04-08 | lat: 20.0 lon: 87.5
Duration: 34 days | Starting date: 1995-05-16 | lat: 20.0 lon: 87.5
Duration: 41 days | Starting date: 1996-04-27 | lat: 20.0 lon: 87.5
Duration: 15 days | Starting date: 1997-05-03 | lat: 20.0 lon: 87.5
Duration: 25 days | Starting date: 1997-05-19 | lat: 20.0 lon: 87.5
Duration: 24 days | Starting date: 1998-05-19 | lat: 20.0 lon: 87.5
Duration: 8 days | Starting date: 1998-06-13 | lat: 20.0 lon: 87.5
Duration: 1 days | Starting date: 1999-03-18 | lat: 20.0 lon: 87.5
Duration: 34 days | Starting date: 1999-04-05 | lat: 20.0 lon: 87.5
Duration: 15 days | Starting date: 2000-04-18 | lat: 20.0 lon: 87.5
Duration: 11 days | Starting date: 2000-05-24 | lat: 20.0 lon: 87.5
Duration: 16 days | Starting date: 2001-05-14 | lat: 20.0 lon: 87.5
Duration: 16 days | Starting date: 2002-04-15 | lat: 20.0 lon: 87.5
Duration: 14 days | Starting date: 2002-05-02 | lat: 20.0 lon: 87.5
Duration: 13 days | Starting date: 2002-05-18 | lat: 20.0 lon: 87.5
Duration: 19 days | Starting date: 2002-06-27 | lat: 20.0 lon: 87.5
Duration: 30 days | Starting date: 2003-04-10 | lat: 20.0 lon: 87.5
Duration: 1 days | Starting date: 2003-05-12 | lat: 20.0 lon: 87.5
Duration: 30 days | Starting date: 2003-05-16 | lat: 20.0 lon: 87.5
Duration: 1 days | Starting date: 2004-04-28 | lat: 20.0 lon: 87.5
Duration: 17 days | Starting date: 2004-04-30 | lat: 20.0 lon: 87.5
Duration: 22 days | Starting date: 2004-05-19 | lat: 20.0 lon: 87.5
Duration: 49 days | Starting date: 2005-05-03 | lat: 20.0 lon: 87.5
Duration: 1 days | Starting date: 2005-06-22 | lat: 20.0 lon: 87.5
Duration: 12 days | Starting date: 2006-06-08 | lat: 20.0 lon: 87.5
Duration: 23 days | Starting date: 2007-05-21 | lat: 20.0 lon: 87.5
Duration: 2 days | Starting date: 2008-04-11 | lat: 20.0 lon: 87.5
Duration: 7 days | Starting date: 2008-04-16 | lat: 20.0 lon: 87.5
Duration: 42 days | Starting date: 2008-04-25 | lat: 20.0 lon: 87.5
Duration: 24 days | Starting date: 2009-06-07 | lat: 20.0 lon: 87.5
Duration: 1 days | Starting date: 2010-03-28 | lat: 20.0 lon: 87.5
Duration: 3 days | Starting date: 2010-03-31 | lat: 20.0 lon: 87.5
Duration: 1 days | Starting date: 2010-04-05 | lat: 20.0 lon: 87.5
Duration: 42 days | Starting date: 2010-04-09 | lat: 20.0 lon: 87.5
Duration: 20 days | Starting date: 2010-05-24 | lat: 20.0 lon: 87.5
Duration: 8 days | Starting date: 2010-06-15 | lat: 20.0 lon: 87.5
Duration: 28 days | Starting date: 2011-04-29 | lat: 20.0 lon: 87.5
Duration: 42 days | Starting date: 2012-05-06 | lat: 20.0 lon: 87.5
Duration: 5 days | Starting date: 2012-06-25 | lat: 20.0 lon: 87.5
Duration: 10 days | Starting date: 2013-05-16 | lat: 20.0 lon: 87.5
Duration: 7 days | Starting date: 2014-03-28 | lat: 20.0 lon: 87.5
Duration: 22 days | Starting date: 2014-04-18 | lat: 20.0 lon: 87.5
Duration: 12 days | Starting date: 2014-05-12 | lat: 20.0 lon: 87.5
Duration: 21 days | Starting date: 2014-05-28 | lat: 20.0 lon: 87.5
Duration: 17 days | Starting date: 2015-05-19 | lat: 20.0 lon: 87.5
Duration: 7 days | Starting date: 2015-06-07 | lat: 20.0 lon: 87.5
Duration: 2 days | Starting date: 2016-03-30 | lat: 20.0 lon: 87.5
Duration: 45 days | Starting date: 2016-04-03 | lat: 20.0 lon: 87.5
Duration: 51 days | Starting date: 2017-04-18 | lat: 20.0 lon: 87.5
Duration: 3 days | Starting date: 2018-06-09 | lat: 20.0 lon: 87.5
Duration: 8 days | Starting date: 2018-06-13 | lat: 20.0 lon: 87.5
Duration: 35 days | Starting date: 2019-05-03 | lat: 20.0 lon: 87.5
Duration: 12 days | Starting date: 2019-06-09 | lat: 20.0 lon: 87.5
Duration: 10 days | Starting date: 2021-05-14 | lat: 20.0 lon: 87.5
Duration: 13 days | Starting date: 2021-05-27 | lat: 20.0 lon: 87.5
Duration: 31 days | Starting date: 2022-05-10 | lat: 20.0 lon: 87.5
Duration: 9 days | Starting date: 2022-06-11 | lat: 20.0 lon: 87.5
Duration: 14 days | Starting date: 1982-05-11 | lat: 20.0 lon: 90.0
Duration: 5 days | Starting date: 1982-05-27 | lat: 20.0 lon: 90.0
Duration: 7 days | Starting date: 1982-07-01 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 1983-05-15 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1983-05-20 | lat: 20.0 lon: 90.0
Duration: 9 days | Starting date: 1983-05-23 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 1983-06-06 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 1983-06-17 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1983-06-23 | lat: 20.0 lon: 90.0
Duration: 21 days | Starting date: 1984-04-26 | lat: 20.0 lon: 90.0
Duration: 8 days | Starting date: 1984-05-19 | lat: 20.0 lon: 90.0
Duration: 11 days | Starting date: 1985-05-08 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1985-05-25 | lat: 20.0 lon: 90.0
Duration: 7 days | Starting date: 1985-05-27 | lat: 20.0 lon: 90.0
Duration: 5 days | Starting date: 1986-05-11 | lat: 20.0 lon: 90.0
Duration: 13 days | Starting date: 1986-05-17 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1986-05-31 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1986-06-02 | lat: 20.0 lon: 90.0
Duration: 10 days | Starting date: 1986-06-04 | lat: 20.0 lon: 90.0
Duration: 22 days | Starting date: 1987-05-11 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 1987-06-05 | lat: 20.0 lon: 90.0
Duration: 4 days | Starting date: 1987-06-12 | lat: 20.0 lon: 90.0
Duration: 14 days | Starting date: 1987-06-17 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1987-07-02 | lat: 20.0 lon: 90.0
Duration: 12 days | Starting date: 1988-05-05 | lat: 20.0 lon: 90.0
Duration: 9 days | Starting date: 1988-05-23 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1988-06-03 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1988-06-05 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 1990-05-16 | lat: 20.0 lon: 90.0
Duration: 8 days | Starting date: 1990-05-19 | lat: 20.0 lon: 90.0
Duration: 6 days | Starting date: 1990-05-28 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 1991-04-30 | lat: 20.0 lon: 90.0
Duration: 4 days | Starting date: 1991-05-07 | lat: 20.0 lon: 90.0
Duration: 17 days | Starting date: 1991-05-13 | lat: 20.0 lon: 90.0
Duration: 10 days | Starting date: 1992-05-31 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 1992-06-11 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 1994-04-21 | lat: 20.0 lon: 90.0
Duration: 6 days | Starting date: 1994-04-25 | lat: 20.0 lon: 90.0
Duration: 19 days | Starting date: 1994-05-02 | lat: 20.0 lon: 90.0
Duration: 11 days | Starting date: 1994-05-26 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1994-06-08 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1995-04-03 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 1995-04-08 | lat: 20.0 lon: 90.0
Duration: 27 days | Starting date: 1995-04-12 | lat: 20.0 lon: 90.0
Duration: 17 days | Starting date: 1995-05-17 | lat: 20.0 lon: 90.0
Duration: 16 days | Starting date: 1995-06-04 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 1996-05-02 | lat: 20.0 lon: 90.0
Duration: 19 days | Starting date: 1996-05-08 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 1996-05-28 | lat: 20.0 lon: 90.0
Duration: 5 days | Starting date: 1996-06-01 | lat: 20.0 lon: 90.0
Duration: 16 days | Starting date: 1997-05-01 | lat: 20.0 lon: 90.0
Duration: 4 days | Starting date: 1997-05-20 | lat: 20.0 lon: 90.0
Duration: 12 days | Starting date: 1997-05-27 | lat: 20.0 lon: 90.0
Duration: 18 days | Starting date: 1998-04-30 | lat: 20.0 lon: 90.0
Duration: 24 days | Starting date: 1998-05-19 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 1998-06-14 | lat: 20.0 lon: 90.0
Duration: 6 days | Starting date: 1998-06-16 | lat: 20.0 lon: 90.0
Duration: 34 days | Starting date: 1999-04-05 | lat: 20.0 lon: 90.0
Duration: 15 days | Starting date: 2000-04-18 | lat: 20.0 lon: 90.0
Duration: 9 days | Starting date: 2000-05-25 | lat: 20.0 lon: 90.0
Duration: 13 days | Starting date: 2001-05-15 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2002-04-18 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2002-04-22 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2002-04-26 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2002-04-30 | lat: 20.0 lon: 90.0
Duration: 10 days | Starting date: 2002-05-04 | lat: 20.0 lon: 90.0
Duration: 6 days | Starting date: 2002-05-19 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2002-05-26 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2002-05-30 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2002-06-26 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2002-07-01 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2002-07-05 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2002-07-08 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2002-07-12 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2002-07-14 | lat: 20.0 lon: 90.0
Duration: 4 days | Starting date: 2003-04-11 | lat: 20.0 lon: 90.0
Duration: 23 days | Starting date: 2003-04-17 | lat: 20.0 lon: 90.0
Duration: 16 days | Starting date: 2003-05-19 | lat: 20.0 lon: 90.0
Duration: 9 days | Starting date: 2003-06-05 | lat: 20.0 lon: 90.0
Duration: 20 days | Starting date: 2004-04-26 | lat: 20.0 lon: 90.0
Duration: 8 days | Starting date: 2004-05-17 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2004-05-26 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2004-06-05 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2005-05-05 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2005-05-07 | lat: 20.0 lon: 90.0
Duration: 32 days | Starting date: 2005-05-09 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2005-06-11 | lat: 20.0 lon: 90.0
Duration: 8 days | Starting date: 2005-06-15 | lat: 20.0 lon: 90.0
Duration: 6 days | Starting date: 2006-06-08 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2006-06-15 | lat: 20.0 lon: 90.0
Duration: 14 days | Starting date: 2007-05-22 | lat: 20.0 lon: 90.0
Duration: 7 days | Starting date: 2007-06-06 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2008-04-07 | lat: 20.0 lon: 90.0
Duration: 4 days | Starting date: 2008-04-10 | lat: 20.0 lon: 90.0
Duration: 39 days | Starting date: 2008-04-16 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2008-05-28 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2008-06-01 | lat: 20.0 lon: 90.0
Duration: 11 days | Starting date: 2009-06-08 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2009-06-21 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2009-06-29 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2010-03-30 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2010-04-01 | lat: 20.0 lon: 90.0
Duration: 42 days | Starting date: 2010-04-09 | lat: 20.0 lon: 90.0
Duration: 17 days | Starting date: 2010-05-25 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2010-06-15 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2010-06-20 | lat: 20.0 lon: 90.0
Duration: 3 days | Starting date: 2011-05-02 | lat: 20.0 lon: 90.0
Duration: 13 days | Starting date: 2011-05-07 | lat: 20.0 lon: 90.0
Duration: 5 days | Starting date: 2011-05-21 | lat: 20.0 lon: 90.0
Duration: 24 days | Starting date: 2012-05-06 | lat: 20.0 lon: 90.0
Duration: 7 days | Starting date: 2012-06-02 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2012-06-10 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2012-06-15 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2012-06-25 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2012-06-29 | lat: 20.0 lon: 90.0
Duration: 10 days | Starting date: 2013-05-16 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2014-03-31 | lat: 20.0 lon: 90.0
Duration: 22 days | Starting date: 2014-04-19 | lat: 20.0 lon: 90.0
Duration: 12 days | Starting date: 2014-05-12 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2014-05-25 | lat: 20.0 lon: 90.0
Duration: 21 days | Starting date: 2014-05-27 | lat: 20.0 lon: 90.0
Duration: 13 days | Starting date: 2015-05-22 | lat: 20.0 lon: 90.0
Duration: 4 days | Starting date: 2015-06-07 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2016-04-05 | lat: 20.0 lon: 90.0
Duration: 41 days | Starting date: 2016-04-08 | lat: 20.0 lon: 90.0
Duration: 13 days | Starting date: 2017-04-19 | lat: 20.0 lon: 90.0
Duration: 22 days | Starting date: 2017-05-06 | lat: 20.0 lon: 90.0
Duration: 9 days | Starting date: 2017-05-30 | lat: 20.0 lon: 90.0
Duration: 7 days | Starting date: 2018-06-14 | lat: 20.0 lon: 90.0
Duration: 32 days | Starting date: 2019-05-04 | lat: 20.0 lon: 90.0
Duration: 9 days | Starting date: 2019-06-10 | lat: 20.0 lon: 90.0
Duration: 8 days | Starting date: 2021-05-15 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2021-05-24 | lat: 20.0 lon: 90.0
Duration: 12 days | Starting date: 2021-05-27 | lat: 20.0 lon: 90.0
Duration: 7 days | Starting date: 2022-05-12 | lat: 20.0 lon: 90.0
Duration: 10 days | Starting date: 2022-05-21 | lat: 20.0 lon: 90.0
Duration: 1 days | Starting date: 2022-06-02 | lat: 20.0 lon: 90.0
Duration: 11 days | Starting date: 2022-06-04 | lat: 20.0 lon: 90.0
Duration: 2 days | Starting date: 2022-06-16 | lat: 20.0 lon: 90.0
Duration: 6 days | Starting date: 1982-05-11 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 1982-05-19 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1982-05-31 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1982-07-02 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1982-07-05 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1983-05-15 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1983-05-17 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 1983-05-24 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1984-04-28 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 1984-05-01 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1984-05-12 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1984-05-15 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1984-05-20 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1984-05-24 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 1985-05-10 | lat: 20.0 lon: 92.5
Duration: 5 days | Starting date: 1986-05-09 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1986-05-19 | lat: 20.0 lon: 92.5
Duration: 6 days | Starting date: 1986-05-22 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1986-06-05 | lat: 20.0 lon: 92.5
Duration: 22 days | Starting date: 1987-05-10 | lat: 20.0 lon: 92.5
Duration: 8 days | Starting date: 1988-05-06 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 1988-05-27 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1991-05-10 | lat: 20.0 lon: 92.5
Duration: 14 days | Starting date: 1991-05-14 | lat: 20.0 lon: 92.5
Duration: 5 days | Starting date: 1992-06-01 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1992-06-07 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1994-04-22 | lat: 20.0 lon: 92.5
Duration: 5 days | Starting date: 1994-04-26 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 1994-05-05 | lat: 20.0 lon: 92.5
Duration: 10 days | Starting date: 1994-05-11 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1994-05-25 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1994-05-28 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1994-06-03 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1995-04-09 | lat: 20.0 lon: 92.5
Duration: 16 days | Starting date: 1995-04-12 | lat: 20.0 lon: 92.5
Duration: 11 days | Starting date: 1995-04-29 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 1995-05-17 | lat: 20.0 lon: 92.5
Duration: 9 days | Starting date: 1995-05-22 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1996-05-10 | lat: 20.0 lon: 92.5
Duration: 11 days | Starting date: 1996-05-14 | lat: 20.0 lon: 92.5
Duration: 13 days | Starting date: 1997-05-04 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1997-05-19 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1997-05-21 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1997-06-01 | lat: 20.0 lon: 92.5
Duration: 17 days | Starting date: 1998-05-01 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 1998-05-19 | lat: 20.0 lon: 92.5
Duration: 11 days | Starting date: 1998-05-29 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 1998-06-14 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 1999-04-06 | lat: 20.0 lon: 92.5
Duration: 6 days | Starting date: 1999-04-09 | lat: 20.0 lon: 92.5
Duration: 15 days | Starting date: 1999-04-18 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 2000-04-19 | lat: 20.0 lon: 92.5
Duration: 5 days | Starting date: 2000-04-27 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2001-05-15 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2001-05-20 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2002-04-16 | lat: 20.0 lon: 92.5
Duration: 6 days | Starting date: 2002-04-23 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2002-05-04 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2002-05-20 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2002-05-23 | lat: 20.0 lon: 92.5
Duration: 9 days | Starting date: 2003-04-08 | lat: 20.0 lon: 92.5
Duration: 12 days | Starting date: 2003-04-18 | lat: 20.0 lon: 92.5
Duration: 10 days | Starting date: 2003-05-02 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 2003-05-29 | lat: 20.0 lon: 92.5
Duration: 23 days | Starting date: 2004-04-19 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2004-05-16 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2004-05-19 | lat: 20.0 lon: 92.5
Duration: 14 days | Starting date: 2005-05-11 | lat: 20.0 lon: 92.5
Duration: 8 days | Starting date: 2005-05-26 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2005-06-04 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2005-06-07 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2005-06-12 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2005-06-20 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2007-05-27 | lat: 20.0 lon: 92.5
Duration: 6 days | Starting date: 2007-05-30 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 2008-04-17 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2008-04-25 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2008-05-02 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2008-05-10 | lat: 20.0 lon: 92.5
Duration: 5 days | Starting date: 2008-05-20 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2009-06-08 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2010-04-01 | lat: 20.0 lon: 92.5
Duration: 38 days | Starting date: 2010-04-11 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 2010-06-01 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2010-06-08 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 2011-05-09 | lat: 20.0 lon: 92.5
Duration: 15 days | Starting date: 2012-05-04 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 2012-05-23 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2012-06-06 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2013-05-18 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2014-04-13 | lat: 20.0 lon: 92.5
Duration: 20 days | Starting date: 2014-04-19 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 2014-05-13 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2014-05-25 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2014-05-31 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2014-06-04 | lat: 20.0 lon: 92.5
Duration: 3 days | Starting date: 2014-06-11 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 2015-05-26 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 2015-05-31 | lat: 20.0 lon: 92.5
Duration: 2 days | Starting date: 2016-04-05 | lat: 20.0 lon: 92.5
Duration: 21 days | Starting date: 2016-04-12 | lat: 20.0 lon: 92.5
Duration: 14 days | Starting date: 2016-05-04 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2017-05-03 | lat: 20.0 lon: 92.5
Duration: 22 days | Starting date: 2017-05-07 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2017-06-02 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2017-06-05 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2017-06-07 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2018-06-16 | lat: 20.0 lon: 92.5
Duration: 30 days | Starting date: 2019-05-03 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2019-06-13 | lat: 20.0 lon: 92.5
Duration: 7 days | Starting date: 2021-05-15 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2021-05-23 | lat: 20.0 lon: 92.5
Duration: 4 days | Starting date: 2021-05-28 | lat: 20.0 lon: 92.5
Duration: 1 days | Starting date: 2021-06-03 | lat: 20.0 lon: 92.5

In [ ]:
df.to_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/Basic_heatwave_or.csv',index=False)

In [ ]:
# using tmax and tmin

In [ ]:
df=pd.read_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/Basic_heatwave.csv')

In [ ]:
from tqdm.auto import tqdm

duration = 0
index_list = []

for lat in tqdm(lat_values, desc='Latitudes',leave=True):
    for lon in tqdm(lon_values, desc='Longitudes',leave=False):
        for date in tqdm(dates, desc='Dates', leave=False):
            date_mask = df['time'] == date
            lat_mask = df['latitude'] == lat
            lon_mask = df['longitude'] == lon
            
            if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() and (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
                duration += 1
                index_list.extend(df[date_mask & lat_mask & lon_mask].index)
            else:
                if duration >= 1:
                    date_mask=df['time'].isin(df['time'][index_list[:]])
                    df_check=df[date_mask]
                    if (df_check['Heatwave'].values==1).any():
                        df.loc[index_list,'Heatwave']=1
                        print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])
                        
                        

In [ ]:
df.to_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/Basic_heatwave_and.csv',index=False)

In [ ]:
sanjid

In [ ]:
in['3456','4589','2345','5694','8765']

In [ ]:
date_mask = df['time'] == '2021-04-01'
df1=df[date_mask]
df1

for lat in lat_values:
    for lon in lon_values:
            lat_mask = df['latitude'] == lat
            lon_mask = df['longitude'] == lon
#             any heatwave value is 1 ? then its 1


In [ ]:
index_list=[3456,4589,2345,5694,8765]
date_masks = df['time'].isin(df['time'][index_list[:]])
df_check = df[date_masks]
df_check

In [ ]:
#temperature greater than 95th percentile.


In [ ]:
from tqdm.auto import tqdm

duration = 0
index_list = []

for lat in tqdm(lat_values, desc='Latitudes',leave=True):
    for lon in tqdm(lon_values, desc='Longitudes',leave=False):
        for date in tqdm(dates, desc='Dates', leave=False):
            date_mask = df['time'] == date
            lat_mask = df['latitude'] == lat
            lon_mask = df['longitude'] == lon
            
            if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() and (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
                duration += 1
                index=df[date_mask & lat_mask & lon_mask].index
                index_list.extend(index)
                
                df.loc[index, 'Heatwave'] = 1
                
            else:
                if duration>=1:
                    print('Duration:',duration,'days |','lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])
                    duration = 0
                    index_list = []


In [ ]:
from tqdm.auto import tqdm

duration = 0
index_list = []

for lat in tqdm(lat_values, desc='Latitudes',leave=True):
    for lon in tqdm(lon_values, desc='Longitudes',leave=False):
        for date in tqdm(dates, desc='Dates', leave=False):
            date_mask = df['time'] == date
            lat_mask = df['latitude'] == lat
            lon_mask = df['longitude'] == lon
            
            if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() or(df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
                duration += 1
                index=df[date_mask & lat_mask & lon_mask].index
                index_list.extend(index)
                
                df.loc[index, 'Heatwave'] = 1
                
            else:
                if duration>=1:
                    print('Duration:',duration,'days |','Starting date:',df['time'][index_list[0]],'| lat:',df['latitude'][index_list[0]],'lon:',df['longitude'][index_list[0]])
                    duration = 0
                    index_list = []


In [ ]:
df

In [ ]:
sanjid

In [ ]:
# minumum 3day in a row

In [ ]:
# If we take consecutive three days as a criteria then it fails to detect any heatwave over sylhet.

In [ ]:
# from tqdm.auto import tqdm

# consecutive_days = 0
# index_list = []

# for lat in tqdm(lat_values, desc='Latitudes',leave=True):
#     for lon in tqdm(lon_values, desc='Longitudes',leave=False):
#         for date in tqdm(dates, desc='Dates', leave=False):
#             date_mask = df['time'] == date
#             lat_mask = df['latitude'] == lat
#             lon_mask = df['longitude'] == lon
            
#             if (df[date_mask & lat_mask & lon_mask]['mx2t'].values >= 307.054055).any() and (df[date_mask & lat_mask & lon_mask]['mn2t'].values >= 300.864264).any():
#                 consecutive_days += 1
#                 index_list.extend(df[date_mask & lat_mask & lon_mask].index)
#             else:
#                 consecutive_days = 0
#                 index_list = []
            
#             if consecutive_days >= 3:
#                 df.loc[index_list, 'Heatwave'] = 1
#                 if consecutive_days==3:
#                     print(index_list[0],"----",df['latitude'][index_list[0]],df['longitude'][index_list[0]])


Latitudes:   0%|          | 0/4 [00:00<?, ?it/s]
Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
6123 ---- 25.0 87.5
6591 ---- 25.0 87.5
10779 ---- 25.0 87.5
19323 ---- 25.0 87.5
23799 ---- 25.0 87.5
28395 ---- 25.0 87.5
50055 ---- 25.0 87.5
63135 ---- 25.0 87.5
63327 ---- 25.0 87.5
72015 ---- 25.0 87.5
76191 ---- 25.0 87.5
98223 ---- 25.0 87.5
102351 ---- 25.0 87.5
106971 ---- 25.0 87.5
107115 ---- 25.0 87.5
124779 ---- 25.0 87.5
129003 ---- 25.0 87.5
137535 ---- 25.0 87.5
137655 ---- 25.0 87.5
137763 ---- 25.0 87.5
150855 ---- 25.0 87.5
168507 ---- 25.0 87.5
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
6138 ---- 22.5 87.5
6186 ---- 22.5 87.5
6582 ---- 22.5 87.5
10530 ---- 22.5 87.5
14766 ---- 22.5 87.5
14838 ---- 22.5 87.5
19146 ---- 22.5 87.5
19290 ---- 22.5 87.5
23814 ---- 22.5 87.5
28074 ---- 22.5 87.5
28242 ---- 22.5 87.5
32226 ---- 22.5 87.5
32418 ---- 22.5 87.5
41178 ---- 22.5 87.5
45294 ---- 22.5 87.5
45546 ---- 22.5 87.5
58458 ---- 22.5 87.5
58758 ---- 22.5 87.5
62862 ---- 22.5 87.5
63162 ---- 22.5 87.5
63342 ---- 22.5 87.5
67482 ---- 22.5 87.5
71994 ---- 22.5 87.5
76194 ---- 22.5 87.5
80394 ---- 22.5 87.5
84714 ---- 22.5 87.5
85026 ---- 22.5 87.5
89382 ---- 22.5 87.5
93594 ---- 22.5 87.5
93702 ---- 22.5 87.5
94314 ---- 22.5 87.5
98154 ---- 22.5 87.5
98238 ---- 22.5 87.5
102354 ---- 22.5 87.5
106890 ---- 22.5 87.5
111510 ---- 22.5 87.5
115662 ---- 22.5 87.5
115746 ---- 22.5 87.5
115818 ---- 22.5 87.5
120138 ---- 22.5 87.5
124674 ---- 22.5 87.5
128406 ---- 22.5 87.5
128538 ---- 22.5 87.5
128658 ---- 22.5 87.5
128850 ---- 22.5 87.5
133074 ---- 22.5 87.5
133170 ---- 22.5 87.5
137478 ---- 22.5 87.5
137574 ---- 22.5 87.5
137994 ---- 22.5 87.5
141942 ---- 22.5 87.5
146214 ---- 22.5 87.5
146502 ---- 22.5 87.5
150702 ---- 22.5 87.5
150906 ---- 22.5 87.5
155010 ---- 22.5 87.5
159402 ---- 22.5 87.5
159606 ---- 22.5 87.5
164154 ---- 22.5 87.5
168246 ---- 22.5 87.5
168306 ---- 22.5 87.5
168522 ---- 22.5 87.5
176970 ---- 22.5 87.5
177186 ---- 22.5 87.5
181302 ---- 22.5 87.5
181518 ---- 22.5 87.5
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
23791 ---- 22.5 90.0
28267 ---- 22.5 90.0
58459 ---- 22.5 90.0
62803 ---- 22.5 90.0
67483 ---- 22.5 90.0
76291 ---- 22.5 90.0
76363 ---- 22.5 90.0
80335 ---- 22.5 90.0
98167 ---- 22.5 90.0
102379 ---- 22.5 90.0
106915 ---- 22.5 90.0
107011 ---- 22.5 90.0
107095 ---- 22.5 90.0
107191 ---- 22.5 90.0
124711 ---- 22.5 90.0
124783 ---- 22.5 90.0
128419 ---- 22.5 90.0
128647 ---- 22.5 90.0
128995 ---- 22.5 90.0
137467 ---- 22.5 90.0
137587 ---- 22.5 90.0
137719 ---- 22.5 90.0
146575 ---- 22.5 90.0
150715 ---- 22.5 90.0
150919 ---- 22.5 90.0
154747 ---- 22.5 90.0
159451 ---- 22.5 90.0
164143 ---- 22.5 90.0
168343 ---- 22.5 90.0
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Longitudes:   0%|          | 0/3 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]
Dates:   0%|          | 0/15340 [00:00<?, ?it/s]

In [ ]:
df.to_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/merged_df_v2.csv')

In [ ]:
df=pd.read_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/merged_df_v2.csv')

In [ ]:
df

In [ ]:
def remove_column(df, column_to_remove):
    # Remove the specified column from the DataFrame
    df = df.drop(column_to_remove, axis=1)
    return df


column_to_remove = 'Unnamed: 0'
df = remove_column(df, column_to_remove)

In [ ]:
6123
6591
10779
19323
23799
28395
50055
63135
63327
72015
76191
98223
102351
106971
107115
124779
129003
137535
137655
137763
150855
168507

In [ ]:
df['latitude'][6138]

In [ ]:
# df['time']=pd.to_datetime(df['time'])
# 
df1=df

In [ ]:
df.set_index('time',inplace=True)

In [ ]:
df

In [ ]:
df1

In [ ]:
df1

In [ ]:
df=pd.read_csv('/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/ERA 5 /Preprocessed data/merged_df_v2.csv')

In [ ]:
df

In [ ]:
df.set_index('time',inplace=True)

In [ ]:
df_march=df['2021-05-01':'2021-05-30']
import pandas as pd

# Assuming df is your DataFrame
df_march1 = df_march[(df_march['latitude'] == 25) & (df_march['longitude'] == 90)]


In [ ]:
df_march1

In [ ]:
# df_march1=df['2021-04-01':'2021-04-01']

In [ ]:
df_march.index.unique().tolist()

In [ ]:
list=df_march.index.unique().tolist()


In [ ]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import cartopy.feature as cf
import cartopy.crs as ccrs
import cartopy.mpl.ticker as cticker

from cartopy.util import add_cyclic_point
from matplotlib import animation
from tqdm.auto import tqdm
from datetime import datetime,timedelta

In [ ]:
import tqdm.auto as tqdm
# (52,135 )
row = 8
col = 4

fig, axs = plt.subplots(row, col, figsize=(52,135 ), dpi=100,subplot_kw={'projection': ccrs.PlateCarree()})

for i in range(row):
    for j in range(col):
        idx = i * col + j
        if idx < len(list):
            daily_df = df_march[list[idx]:list[idx]]
            unique_lat = daily_df['latitude'].unique()
            unique_lon = daily_df['longitude'].unique()
            array = daily_df['mx2t'].values.reshape(len(unique_lat), len(unique_lon))

            # Create a Cartopy PlateCarree projection
            projection = ccrs.PlateCarree()

            # Create a subplot with adjusted aspect ratio
            ax = axs[i, j]

            # Plot the temperature data using pcolormesh
            cax = ax.pcolormesh(unique_lon, unique_lat, array, transform=projection, cmap='coolwarm')

            # Set title and labels
            ax.set_title(f'Day {list[idx]}',fontsize=50)  # Assuming list contains days

            # Add coastlines and gridlines
            ax.coastlines()
            ax.add_feature(cf.BORDERS)
            ax.gridlines(draw_labels=True)




# Add a colorbar
fig.subplots_adjust(right=0.9)
cbar_ax = fig.add_axes([1, 0, 0.02,1])
cbar = plt.colorbar(cax, cax=cbar_ax, orientation='vertical', label='Temperature (K)')

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(hspace=0.15)
# Show the plot
plt.show()


In [ ]:
df_jan=df['2021-05-01':'2021-05-30']
df_jan.index.unique().tolist()
list=df_jan.index.unique().tolist()


In [ ]:
import tqdm.auto as tqdm
# (52,135 )
row = 8
col = 4

fig, axs = plt.subplots(row, col, figsize=(52,135 ), dpi=100,subplot_kw={'projection': ccrs.PlateCarree()})

for i in range(row):
    for j in range(col):
        idx = i * col + j
        if idx < len(list):
            daily_df = df_jan[list[idx]:list[idx]]
            unique_lat = daily_df['latitude'].unique()
            unique_lon = daily_df['longitude'].unique()
            array = daily_df['t2m'].values.reshape(len(unique_lat), len(unique_lon))

            # Create a Cartopy PlateCarree projection
            projection = ccrs.PlateCarree()

            # Create a subplot with adjusted aspect ratio
            ax = axs[i, j]

            # Plot the temperature data using pcolormesh
            cax = ax.pcolormesh(unique_lon, unique_lat, array, transform=projection, cmap='coolwarm')

            # Set title and labels
            ax.set_title(f'Day {list[idx]}',fontsize=50)  # Assuming list contains days

            # Add coastlines and gridlines
            ax.coastlines()
            ax.add_feature(cf.BORDERS)
            ax.gridlines(draw_labels=True)




# Add a colorbar
fig.subplots_adjust(right=0.9)
cbar_ax = fig.add_axes([1, 0, 0.02,1])
cbar = plt.colorbar(cax, cax=cbar_ax, orientation='vertical', label='Temperature (K)')

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(hspace=0.15)
# Show the plot
plt.show()


In [ ]:
import tqdm.auto as tqdm
import matplotlib.gridspec as gridspec

row = 8
col = 4

fig = plt.figure(figsize=(25, 25), dpi=100)
spec = gridspec.GridSpec(row, col, figure=fig, wspace=0, hspace=0)

for i in range(row):
    for j in range(col):
        idx = i * col + j
        if idx < len(list):
            daily_df = df_march[list[idx]:list[idx]]
            unique_lat = daily_df['latitude'].unique()
            unique_lon = daily_df['longitude'].unique()
            array = daily_df['mx2t'].values.reshape(len(unique_lat), len(unique_lon))

            # Create a Cartopy PlateCarree projection
            projection = ccrs.PlateCarree()

            # Create a subplot
            ax = fig.add_subplot(spec[i, j], projection=projection)

            # Plot the temperature data using pcolormesh
            cax = ax.pcolormesh(unique_lon, unique_lat, array, transform=projection, cmap='coolwarm')

            # Set title and labels
            ax.set_title(f'Day {list[idx]}')  # Assuming list contains days
            ax.set_xlabel('Longitude')
            ax.set_ylabel('Latitude')

            # Add coastlines and gridlines
            ax.coastlines()
            ax.add_feature(cf.BORDERS)
            ax.gridlines(draw_labels=True)

# Add a colorbar
fig.subplots_adjust(right=0.9)
cbar_ax = fig.add_axes([0.95, 0.15, 0.02, 0.7])
cbar = plt.colorbar(cax, cax=cbar_ax, orientation='vertical', label='Temperature (K)')

# Show the plot
plt.show()


In [ ]:
import warnings
warnings.filterwarnings("ignore")

row = 8
fig, axs = plt.subplots(row, 4, figsize=(25, 25), dpi=200, subplot_kw={'projection': ccrs.PlateCarree()})
for i in range(0,len(list)):
    daily_df=df_march[list[i]:list[i]]  # Assuming you have a 'day' column in your DataFrame
    unique_lat = daily_df['latitude'].unique()
    unique_lon = daily_df['longitude'].unique()
    array = daily_df['mx2t'].values.reshape(len(unique_lat), len(unique_lon))

    # Calculate row and col indices for subplot
#     row_idx = i // 4
#     col_idx = i % 4

    # Create a Cartopy PlateCarree projection
    projection = ccrs.PlateCarree()

    # Create a subplot
#     ax = axs[row_idx, col_idx]

    # Plot the temperature data using pcolormesh
    cax = ax.pcolormesh(unique_lon, unique_lat, array, transform=projection, cmap='coolwarm')

    # Set title and labels
    ax.set_title(f'Day {day}')
    ax.set_xlabel('Longitude')
    ax.set_ylabel('Latitude')

    # Add coastlines and gridlines
    ax.coastlines()
    ax.add_feature(cf.BORDERS)
    ax.gridlines(draw_labels=True)

# Add a colorbar
fig.subplots_adjust(right=0.9)
cbar_ax = fig.add_axes([1, 0, 0.04,1]) 
cbar = plt.colorbar(cax, cax=cbar_ax, orientation='vertical', label='Temperature (K)')

# Adjust layout
plt.tight_layout()

# Show the plot
plt.show()


In [ ]:
import warnings
warnings.filterwarnings("ignore")



# Assuming you have the t2m_df DataFrame with "latitude", "longitude", and "t2m" columns

unique_lat = t2m_df2['latitude'].unique()
unique_lon = t2m_df2['longitude'].unique()

# Reshape the t2m data into a 2D array matching the grid
t2m_array = t2m_df2['mx2t'].values.reshape(len(unique_lat), len(unique_lon))

# Create a Cartopy PlateCarree projection
projection = ccrs.PlateCarree()

# Create a figure and axis
fig, ax = plt.subplots(subplot_kw={'projection': projection})

# Plot the temperature data using pcolormesh
cax = ax.pcolormesh(unique_lon, unique_lat, t2m_array, transform=projection, cmap='coolwarm')

# Add colorbar
cbar = plt.colorbar(cax, ax=ax, orientation='vertical', pad=0.05, label='Temperature (K)')

# Set title and labels
ax.set_title('ERA5 2m Temperature')
ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')

# Add coastlines and gridlines
ax.coastlines()
ax.add_feature(cfeature.BORDERS)
ax.gridlines(draw_labels=True)

# Show the plot
plt.show()


In [ ]:
contourf_objects = []
cyclone_number = 17
sin_cyc = pre_data[pre_data['NUMBER'] == cyclone_number]
cyclone_data = sin_cyc[['NUMBER', 'ISO_TIME', 'lat', 'lon']].reset_index()
time_stamps=cyclone_data.ISO_TIME.to_list()
row=math.ceil((len(time_stamps)/6)/4)
fig, axs = plt.subplots(row, 4, figsize=(15, 15), dpi=100, subplot_kw={'projection': ccrs.PlateCarree()})

k=0
for i in tqdm(range(row),desc="Plot Loop"):
    for j in range(4):
#         for k in range(0, len(time_stamps), 3):

                if not cyclone_data.empty:
                    target_date = cyclone_data.ISO_TIME[k]
                    target_cyclone_date = datetime.strptime(target_date, "%Y-%m-%d %H:%M:%S").strftime("%Y-%m-%dT%H")
                    index = slp_time.index(target_cyclone_date)
                    
            

                    axs[i,j].plot(cyclone_data.lon, cyclone_data.lat, '-o', markersize=1.5, color='white', transform=ccrs.PlateCarree())
                    axs[i,j].set_extent([78, 100, 0, 25], crs=ccrs.PlateCarree())
                    axs[i,j].coastlines(linewidth=1.4)
                    axs[i,j].set_title(f"Time-{target_date}")
                    # ax.gridlines(draw_labels=True)
   
                    # axs[i,j].contourf(lon2d, lat2d, slp_data.msl[index,:,:], cmap='rainbow', extend='both', transform=ccrs.PlateCarree())
                    # Create the contourf plot
                    contourf = axs[i, j].contourf(lon2d, lat2d, slp_data.msl[index, :, :], cmap='rainbow', extend='both', transform=ccrs.PlateCarree())
                    contourf_objects.append(contourf)
                    k+=6
                    if k>=len(time_stamps):
                        break
    if k>= len(time_stamps):
        break


# Create a single colorbar for all subplots
cbar_ax = fig.add_axes([1, 0, 0.04,1])  # Define the position of the colorbar [left, bottom, width, height][1, 0, 0.03, 1])

# Add a colorbar
cbar = fig.colorbar(contourf_objects[0], cax=cbar_ax, orientation='vertical', label='SLP')

# Full title
fig.suptitle("SLP variaion of Cyclone NO:"+str(cyclone_data.NUMBER[0])+'_'+str(cyclone_data.ISO_TIME[0][:7]), fontsize=16, fontweight='bold', y=1) # MUST ADD YEAR RANGE

# Adjust spacing between subplots
fig.tight_layout()

plt.savefig("/mnt/1A42C1DD42C1BE2F/MyProjects/ML_TCBOB/Data/Preprocessed data/figures for Dataset Report-2 [September 8, 2023] Task-2/Cyclone NO:17_1996-12.png")


In [ ]:
https://community.wmo.int/en/activity-areas/imop/wmo-no_8
https://confluence.ecmwf.int/pages/viewpage.action?pageId=171411214
    https://earthscience.stackexchange.com/questions/24156/era5-single-level-calculate-relative-humidity
        
    
